// Generated by the protocol buffer compiler. DO NOT EDIT!

package com.appenginefan.toolkit.persistence;

public final class TestData {
  private TestData() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static final class Person
      extends com.google.protobuf.GeneratedMessage {
    // Use Person.newBuilder() to construct.
    private Person() {
    }

    private static final Person defaultInstance =
        new Person();

    public static Person getDefaultInstance() {
      return defaultInstance;
    }

    public Person getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.appenginefan.toolkit.persistence.TestData.internal_static_javatests_Person_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
      return com.appenginefan.toolkit.persistence.TestData.internal_static_javatests_Person_fieldAccessorTable;
    }

    // required string name = 1;
    private boolean hasName;

    private java.lang.String name_ = "";

    public boolean hasName() {
      return hasName;
    }

    public java.lang.String getName() {
      return name_;
    }

    // optional string email = 2;
    private boolean hasEmail;

    private java.lang.String email_ = "";

    public boolean hasEmail() {
      return hasEmail;
    }

    public java.lang.String getEmail() {
      return email_;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasName)
        return false;
      return true;
    }

    @Override
    public void writeTo(
        com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (hasName()) {
        output.writeString(1, getName());
      }
      if (hasEmail()) {
        output.writeString(2, getEmail());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;

    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1)
        return size;

      size = 0;
      if (hasName()) {
        size +=
            com.google.protobuf.CodedOutputStream
                .computeStringSize(1, getName());
      }
      if (hasEmail()) {
        size +=
            com.google.protobuf.CodedOutputStream
                .computeStringSize(2, getEmail());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder()
          .mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder()
          .mergeFrom(data, extensionRegistry).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input,
          extensionRegistry).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }

    public static com.appenginefan.toolkit.persistence.TestData.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input,
          extensionRegistry).buildParsed();
    }

    public static Builder newBuilder() {
      return new Builder();
    }

    public Builder newBuilderForType() {
      return new Builder();
    }

    public static Builder newBuilder(
        com.appenginefan.toolkit.persistence.TestData.Person prototype) {
      return new Builder().mergeFrom(prototype);
    }

    public static final class Builder
        extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using
      // com.appenginefan.toolkit.persistence.TestData.Person.newBuilder()
      private Builder() {
      }

      com.appenginefan.toolkit.persistence.TestData.Person result =
          new com.appenginefan.toolkit.persistence.TestData.Person();

      @Override
      protected com.appenginefan.toolkit.persistence.TestData.Person internalGetResult() {
        return result;
      }

      @Override
      public Builder clear() {
        result =
            new com.appenginefan.toolkit.persistence.TestData.Person();
        return this;
      }

      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.appenginefan.toolkit.persistence.TestData.Person
            .getDescriptor();
      }

      public com.appenginefan.toolkit.persistence.TestData.Person getDefaultInstanceForType() {
        return com.appenginefan.toolkit.persistence.TestData.Person
            .getDefaultInstance();
      }

      public com.appenginefan.toolkit.persistence.TestData.Person build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
              result);
        }
        return buildPartial();
      }

      private com.appenginefan.toolkit.persistence.TestData.Person buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
              result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }

      public com.appenginefan.toolkit.persistence.TestData.Person buildPartial() {
        com.appenginefan.toolkit.persistence.TestData.Person returnMe =
            result;
        result = null;
        return returnMe;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.Message other) {
        if (other instanceof com.appenginefan.toolkit.persistence.TestData.Person) {
          return mergeFrom((com.appenginefan.toolkit.persistence.TestData.Person) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.appenginefan.toolkit.persistence.TestData.Person other) {
        if (other == com.appenginefan.toolkit.persistence.TestData.Person
            .getDefaultInstance())
          return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
            com.google.protobuf.ExtensionRegistry
                .getEmptyRegistry());
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet
                .newBuilder(this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
          case 0:
            this.setUnknownFields(unknownFields.build());
            return this;
          default: {
            if (!parseUnknownField(input, unknownFields,
                extensionRegistry, tag)) {
              this.setUnknownFields(unknownFields.build());
              return this;
            }
            break;
          }
          case 10: {
            setName(input.readString());
            break;
          }
          case 18: {
            setEmail(input.readString());
            break;
          }
          }
        }
      }

      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }

      public java.lang.String getName() {
        return result.getName();
      }

      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }

      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }

      // optional string email = 2;
      public boolean hasEmail() {
        return result.hasEmail();
      }

      public java.lang.String getEmail() {
        return result.getEmail();
      }

      public Builder setEmail(java.lang.String value) {
        result.hasEmail = true;
        result.email_ = value;
        return this;
      }

      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = "";
        return this;
      }
    }

    static {
      com.appenginefan.toolkit.persistence.TestData
          .getDescriptor();
    }
  }

  private static com.google.protobuf.Descriptors.Descriptor internal_static_javatests_Person_descriptor;

  private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_javatests_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String descriptorData =
        "\n\034src/javatests/testdata.proto\022\tjavatest"
            + "s\"%\n\006Person\022\014\n\004name\030\001 \002(\t\022\r\n\005email\030\002 \001(\t"
            + "B2\n$com.appenginefan.toolkit.persistence"
            + "B\010TestDataH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            internal_static_javatests_Person_descriptor =
                getDescriptor().getMessageTypes().get(0);
            internal_static_javatests_Person_fieldAccessorTable =
                new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                    internal_static_javatests_Person_descriptor,
                    new java.lang.String[] { "Name",
                        "Email", },
                    com.appenginefan.toolkit.persistence.TestData.Person.class,
                    com.appenginefan.toolkit.persistence.TestData.Person.Builder.class);
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {},
            assigner);
  }
}
