// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.appenginefan.toolkit.common.data;

public final class ProtoSchema {
  private ProtoSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Message extends
      com.google.protobuf.GeneratedMessage {
    // Use Message.newBuilder() to construct.
    private Message() {}
    
    private static final Message defaultInstance = new Message();
    public static Message getDefaultInstance() {
      return defaultInstance;
    }
    
    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_Message_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_Message_fieldAccessorTable;
    }
    
    // required string payload = 1;
    private boolean hasPayload;
    private java.lang.String payload_ = "";
    public boolean hasPayload() { return hasPayload; }
    public java.lang.String getPayload() { return payload_; }
    
    // required int32 ackToken = 2;
    private boolean hasAckToken;
    private int ackToken_ = 0;
    public boolean hasAckToken() { return hasAckToken; }
    public int getAckToken() { return ackToken_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasPayload) return false;
      if (!hasAckToken) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasPayload()) {
        output.writeString(1, getPayload());
      }
      if (hasAckToken()) {
        output.writeInt32(2, getAckToken());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasPayload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getPayload());
      }
      if (hasAckToken()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getAckToken());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.appenginefan.toolkit.common.data.ProtoSchema.Message prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.appenginefan.toolkit.common.data.ProtoSchema.Message.newBuilder()
      private Builder() {}
      
      com.appenginefan.toolkit.common.data.ProtoSchema.Message result = new com.appenginefan.toolkit.common.data.ProtoSchema.Message();
      
      @Override
      protected com.appenginefan.toolkit.common.data.ProtoSchema.Message internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.appenginefan.toolkit.common.data.ProtoSchema.Message();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.Message.getDescriptor();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Message getDefaultInstanceForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.Message.getDefaultInstance();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Message build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.appenginefan.toolkit.common.data.ProtoSchema.Message buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Message buildPartial() {
        com.appenginefan.toolkit.common.data.ProtoSchema.Message returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appenginefan.toolkit.common.data.ProtoSchema.Message) {
          return mergeFrom((com.appenginefan.toolkit.common.data.ProtoSchema.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.appenginefan.toolkit.common.data.ProtoSchema.Message other) {
        if (other == com.appenginefan.toolkit.common.data.ProtoSchema.Message.getDefaultInstance()) return this;
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        if (other.hasAckToken()) {
          setAckToken(other.getAckToken());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setPayload(input.readString());
              break;
            }
            case 16: {
              setAckToken(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required string payload = 1;
      public boolean hasPayload() {
        return result.hasPayload();
      }
      public java.lang.String getPayload() {
        return result.getPayload();
      }
      public Builder setPayload(java.lang.String value) {
        result.hasPayload = true;
        result.payload_ = value;
        return this;
      }
      public Builder clearPayload() {
        result.hasPayload = false;
        result.payload_ = "";
        return this;
      }
      
      // required int32 ackToken = 2;
      public boolean hasAckToken() {
        return result.hasAckToken();
      }
      public int getAckToken() {
        return result.getAckToken();
      }
      public Builder setAckToken(int value) {
        result.hasAckToken = true;
        result.ackToken_ = value;
        return this;
      }
      public Builder clearAckToken() {
        result.hasAckToken = false;
        result.ackToken_ = 0;
        return this;
      }
    }
    
    static {
      com.appenginefan.toolkit.common.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class Property extends
      com.google.protobuf.GeneratedMessage {
    // Use Property.newBuilder() to construct.
    private Property() {}
    
    private static final Property defaultInstance = new Property();
    public static Property getDefaultInstance() {
      return defaultInstance;
    }
    
    public Property getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_Property_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_Property_fieldAccessorTable;
    }
    
    // required string key = 1;
    private boolean hasKey;
    private java.lang.String key_ = "";
    public boolean hasKey() { return hasKey; }
    public java.lang.String getKey() { return key_; }
    
    // required string value = 2;
    private boolean hasValue;
    private java.lang.String value_ = "";
    public boolean hasValue() { return hasValue; }
    public java.lang.String getValue() { return value_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasKey) return false;
      if (!hasValue) return false;
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (hasKey()) {
        output.writeString(1, getKey());
      }
      if (hasValue()) {
        output.writeString(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getKey());
      }
      if (hasValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.Property parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.appenginefan.toolkit.common.data.ProtoSchema.Property prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.appenginefan.toolkit.common.data.ProtoSchema.Property.newBuilder()
      private Builder() {}
      
      com.appenginefan.toolkit.common.data.ProtoSchema.Property result = new com.appenginefan.toolkit.common.data.ProtoSchema.Property();
      
      @Override
      protected com.appenginefan.toolkit.common.data.ProtoSchema.Property internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.appenginefan.toolkit.common.data.ProtoSchema.Property();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.Property.getDescriptor();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Property getDefaultInstanceForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.Property.getDefaultInstance();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Property build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.appenginefan.toolkit.common.data.ProtoSchema.Property buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.Property buildPartial() {
        com.appenginefan.toolkit.common.data.ProtoSchema.Property returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appenginefan.toolkit.common.data.ProtoSchema.Property) {
          return mergeFrom((com.appenginefan.toolkit.common.data.ProtoSchema.Property)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.appenginefan.toolkit.common.data.ProtoSchema.Property other) {
        if (other == com.appenginefan.toolkit.common.data.ProtoSchema.Property.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readString());
              break;
            }
            case 18: {
              setValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public java.lang.String getKey() {
        return result.getKey();
      }
      public Builder setKey(java.lang.String value) {
        result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = "";
        return this;
      }
      
      // required string value = 2;
      public boolean hasValue() {
        return result.hasValue();
      }
      public java.lang.String getValue() {
        return result.getValue();
      }
      public Builder setValue(java.lang.String value) {
        result.hasValue = true;
        result.value_ = value;
        return this;
      }
      public Builder clearValue() {
        result.hasValue = false;
        result.value_ = "";
        return this;
      }
    }
    
    static {
      com.appenginefan.toolkit.common.data.ProtoSchema.getDescriptor();
    }
  }
  
  public static final class ConnectionState extends
      com.google.protobuf.GeneratedMessage {
    // Use ConnectionState.newBuilder() to construct.
    private ConnectionState() {}
    
    private static final ConnectionState defaultInstance = new ConnectionState();
    public static ConnectionState getDefaultInstance() {
      return defaultInstance;
    }
    
    public ConnectionState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_ConnectionState_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appenginefan.toolkit.common.data.ProtoSchema.internal_static_data_ConnectionState_fieldAccessorTable;
    }
    
    // repeated .data.Message messageQueue = 1;
    private java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Message> messageQueue_ =
      java.util.Collections.emptyList();
    public java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Message> getMessageQueueList() {
      return messageQueue_;
    }
    public int getMessageQueueCount() { return messageQueue_.size(); }
    public com.appenginefan.toolkit.common.data.ProtoSchema.Message getMessageQueue(int index) {
      return messageQueue_.get(index);
    }
    
    // repeated .data.Property connectionProperties = 2;
    private java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Property> connectionProperties_ =
      java.util.Collections.emptyList();
    public java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Property> getConnectionPropertiesList() {
      return connectionProperties_;
    }
    public int getConnectionPropertiesCount() { return connectionProperties_.size(); }
    public com.appenginefan.toolkit.common.data.ProtoSchema.Property getConnectionProperties(int index) {
      return connectionProperties_.get(index);
    }
    
    // required string randomSecret = 3;
    private boolean hasRandomSecret;
    private java.lang.String randomSecret_ = "";
    public boolean hasRandomSecret() { return hasRandomSecret; }
    public java.lang.String getRandomSecret() { return randomSecret_; }
    
    // optional int32 highestAckedMessage = 4;
    private boolean hasHighestAckedMessage;
    private int highestAckedMessage_ = 0;
    public boolean hasHighestAckedMessage() { return hasHighestAckedMessage; }
    public int getHighestAckedMessage() { return highestAckedMessage_; }
    
    @Override
    public final boolean isInitialized() {
      if (!hasRandomSecret) return false;
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Message element : getMessageQueueList()) {
        if (!element.isInitialized()) return false;
      }
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Message element : getMessageQueueList()) {
        output.writeMessage(1, element);
      }
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        output.writeMessage(2, element);
      }
      if (hasRandomSecret()) {
        output.writeString(3, getRandomSecret());
      }
      if (hasHighestAckedMessage()) {
        output.writeInt32(4, getHighestAckedMessage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    @Override
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Message element : getMessageQueueList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      for (com.appenginefan.toolkit.common.data.ProtoSchema.Property element : getConnectionPropertiesList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      if (hasRandomSecret()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getRandomSecret());
      }
      if (hasHighestAckedMessage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getHighestAckedMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.newBuilder()
      private Builder() {}
      
      com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState result = new com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState();
      
      @Override
      protected com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.getDescriptor();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState getDefaultInstanceForType() {
        return com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.getDefaultInstance();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState buildPartial() {
        if (result.messageQueue_ != java.util.Collections.EMPTY_LIST) {
          result.messageQueue_ =
            java.util.Collections.unmodifiableList(result.messageQueue_);
        }
        if (result.connectionProperties_ != java.util.Collections.EMPTY_LIST) {
          result.connectionProperties_ =
            java.util.Collections.unmodifiableList(result.connectionProperties_);
        }
        com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState returnMe = result;
        result = null;
        return returnMe;
      }
      
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState) {
          return mergeFrom((com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState other) {
        if (other == com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.getDefaultInstance()) return this;
        if (!other.messageQueue_.isEmpty()) {
          if (result.messageQueue_.isEmpty()) {
            result.messageQueue_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Message>();
          }
          result.messageQueue_.addAll(other.messageQueue_);
        }
        if (!other.connectionProperties_.isEmpty()) {
          if (result.connectionProperties_.isEmpty()) {
            result.connectionProperties_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Property>();
          }
          result.connectionProperties_.addAll(other.connectionProperties_);
        }
        if (other.hasRandomSecret()) {
          setRandomSecret(other.getRandomSecret());
        }
        if (other.hasHighestAckedMessage()) {
          setHighestAckedMessage(other.getHighestAckedMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return mergeFrom(input,
          com.google.protobuf.ExtensionRegistry.getEmptyRegistry());
      }
      
      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistry extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.appenginefan.toolkit.common.data.ProtoSchema.Message.Builder subBuilder = com.appenginefan.toolkit.common.data.ProtoSchema.Message.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMessageQueue(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.appenginefan.toolkit.common.data.ProtoSchema.Property.Builder subBuilder = com.appenginefan.toolkit.common.data.ProtoSchema.Property.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConnectionProperties(subBuilder.buildPartial());
              break;
            }
            case 26: {
              setRandomSecret(input.readString());
              break;
            }
            case 32: {
              setHighestAckedMessage(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // repeated .data.Message messageQueue = 1;
      public java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Message> getMessageQueueList() {
        return java.util.Collections.unmodifiableList(result.messageQueue_);
      }
      public int getMessageQueueCount() {
        return result.getMessageQueueCount();
      }
      public com.appenginefan.toolkit.common.data.ProtoSchema.Message getMessageQueue(int index) {
        return result.getMessageQueue(index);
      }
      public Builder setMessageQueue(int index, com.appenginefan.toolkit.common.data.ProtoSchema.Message value) {
        result.messageQueue_.set(index, value);
        return this;
      }
      public Builder setMessageQueue(int index, com.appenginefan.toolkit.common.data.ProtoSchema.Message.Builder builderForValue) {
        result.messageQueue_.set(index, builderForValue.build());
        return this;
      }
      public Builder addMessageQueue(com.appenginefan.toolkit.common.data.ProtoSchema.Message value) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Message>();
        }
        result.messageQueue_.add(value);
        return this;
      }
      public Builder addMessageQueue(com.appenginefan.toolkit.common.data.ProtoSchema.Message.Builder builderForValue) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Message>();
        }
        result.messageQueue_.add(builderForValue.build());
        return this;
      }
      public Builder addAllMessageQueue(
          java.lang.Iterable<? extends com.appenginefan.toolkit.common.data.ProtoSchema.Message> values) {
        if (result.messageQueue_.isEmpty()) {
          result.messageQueue_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Message>();
        }
        super.addAll(values, result.messageQueue_);
        return this;
      }
      public Builder clearMessageQueue() {
        result.messageQueue_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .data.Property connectionProperties = 2;
      public java.util.List<com.appenginefan.toolkit.common.data.ProtoSchema.Property> getConnectionPropertiesList() {
        return java.util.Collections.unmodifiableList(result.connectionProperties_);
      }
      public int getConnectionPropertiesCount() {
        return result.getConnectionPropertiesCount();
      }
      public com.appenginefan.toolkit.common.data.ProtoSchema.Property getConnectionProperties(int index) {
        return result.getConnectionProperties(index);
      }
      public Builder setConnectionProperties(int index, com.appenginefan.toolkit.common.data.ProtoSchema.Property value) {
        result.connectionProperties_.set(index, value);
        return this;
      }
      public Builder setConnectionProperties(int index, com.appenginefan.toolkit.common.data.ProtoSchema.Property.Builder builderForValue) {
        result.connectionProperties_.set(index, builderForValue.build());
        return this;
      }
      public Builder addConnectionProperties(com.appenginefan.toolkit.common.data.ProtoSchema.Property value) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Property>();
        }
        result.connectionProperties_.add(value);
        return this;
      }
      public Builder addConnectionProperties(com.appenginefan.toolkit.common.data.ProtoSchema.Property.Builder builderForValue) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Property>();
        }
        result.connectionProperties_.add(builderForValue.build());
        return this;
      }
      public Builder addAllConnectionProperties(
          java.lang.Iterable<? extends com.appenginefan.toolkit.common.data.ProtoSchema.Property> values) {
        if (result.connectionProperties_.isEmpty()) {
          result.connectionProperties_ = new java.util.ArrayList<com.appenginefan.toolkit.common.data.ProtoSchema.Property>();
        }
        super.addAll(values, result.connectionProperties_);
        return this;
      }
      public Builder clearConnectionProperties() {
        result.connectionProperties_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string randomSecret = 3;
      public boolean hasRandomSecret() {
        return result.hasRandomSecret();
      }
      public java.lang.String getRandomSecret() {
        return result.getRandomSecret();
      }
      public Builder setRandomSecret(java.lang.String value) {
        result.hasRandomSecret = true;
        result.randomSecret_ = value;
        return this;
      }
      public Builder clearRandomSecret() {
        result.hasRandomSecret = false;
        result.randomSecret_ = "";
        return this;
      }
      
      // optional int32 highestAckedMessage = 4;
      public boolean hasHighestAckedMessage() {
        return result.hasHighestAckedMessage();
      }
      public int getHighestAckedMessage() {
        return result.getHighestAckedMessage();
      }
      public Builder setHighestAckedMessage(int value) {
        result.hasHighestAckedMessage = true;
        result.highestAckedMessage_ = value;
        return this;
      }
      public Builder clearHighestAckedMessage() {
        result.hasHighestAckedMessage = false;
        result.highestAckedMessage_ = 0;
        return this;
      }
    }
    
    static {
      com.appenginefan.toolkit.common.data.ProtoSchema.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_Message_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_Property_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_Property_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_ConnectionState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_ConnectionState_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\025src/java/schema.proto\022\004data\",\n\007Message" +
      "\022\017\n\007payload\030\001 \002(\t\022\020\n\010ackToken\030\002 \002(\005\"&\n\010P" +
      "roperty\022\013\n\003key\030\001 \002(\t\022\r\n\005value\030\002 \002(\t\"\227\001\n\017" +
      "ConnectionState\022#\n\014messageQueue\030\001 \003(\0132\r." +
      "data.Message\022,\n\024connectionProperties\030\002 \003" +
      "(\0132\016.data.Property\022\024\n\014randomSecret\030\003 \002(\t" +
      "\022\033\n\023highestAckedMessage\030\004 \001(\005B5\n$com.app" +
      "enginefan.toolkit.common.dataB\013ProtoSche" +
      "maH\001";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_data_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_data_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_Message_descriptor,
              new java.lang.String[] { "Payload", "AckToken", },
              com.appenginefan.toolkit.common.data.ProtoSchema.Message.class,
              com.appenginefan.toolkit.common.data.ProtoSchema.Message.Builder.class);
          internal_static_data_Property_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_data_Property_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_Property_descriptor,
              new java.lang.String[] { "Key", "Value", },
              com.appenginefan.toolkit.common.data.ProtoSchema.Property.class,
              com.appenginefan.toolkit.common.data.ProtoSchema.Property.Builder.class);
          internal_static_data_ConnectionState_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_data_ConnectionState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_data_ConnectionState_descriptor,
              new java.lang.String[] { "MessageQueue", "ConnectionProperties", "RandomSecret", "HighestAckedMessage", },
              com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.class,
              com.appenginefan.toolkit.common.data.ProtoSchema.ConnectionState.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
